name 'puppet-nagios'
version '0.0.1'
license 'GPL 3.0'
summary 'A Puppet report handler for sending notifications of failed runs to Nagios via send_nsca'
project_page 'https://github.com/DennisonWilliams/puppet-nagios'
